/**
 * CS 631 Project
 * Roderic Henry & Amruta Abhyankar
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Room } from './room';

export interface TaughtIn { 
    room?: Room;
    time?: string;
    weekday?: number;
}